const MOVIES_ACTION_TYPES = {
  SEARCH_MOVIES_START: 'SEARCH_MOVIES_START',
  SEARCH_MOVIES_FAILED: 'SEARCH_MOVIES_FAILED',
  SEARCH_MOVIES_SUCCESS: 'SEARCH_MOVIES_SUCCESS',
  SET_SEARCH_CRITERIA: 'SET_SEARCH_CRITERIA',
  SET_HAS_MORE_RESULTS: 'SET_HAS_MORE_RESULTS',
  SET_PAGE: 'SET_PAGE',
  LOAD_MORE_MOVIES_START: 'LOAD_MORE_MOVIES_START',
  LOAD_MORE_MOVIES_FAILED: 'LOAD_MORE_MOVIES_FAILED',
  LOAD_MORE_MOVIES_SUCCESS: 'LOAD_MORE_MOVIES_SUCCESS',
  SORT_MOVIES: 'SORT_MOVIES',
};

export default MOVIES_ACTION_TYPES;
